"""Configuration constants for the SayPlan SemPathBench adapter."""

from __future__ import annotations


METHOD_NAME = "SayPlan"
INFERENCE_CONTRACT_VERSION = 2

DEFAULT_MAX_SEARCH_STEPS = 20
DEFAULT_MAX_REPLANS = 5
DEFAULT_MAX_JSON_RETRIES = 2
DEFAULT_GEMINI_TEMPERATURE = 0
DEFAULT_GEMINI_TIMEOUT_SECONDS = 90.0

MAX_PROMPT_ATTRIBUTES = 8
MAX_PROMPT_ATTRIBUTE_CHARS = 120

